StudentsRegistration/StudentsRegistration/Controllers/StudentFeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Common.Models.StudentsPanelModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace StudentsRegistrationPanel.Controllers
{
    public class StudentFeedbackController : Controller
    {
        private readonly IStudentFeedbackService studentFeedbackService;

        public StudentFeedbackController(IStudentFeedbackService studentFeedbackService)
        {
            this.studentFeedbackService = studentFeedbackService;
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> CreateStudentFeedBack(StudentFeedBackForm form)
        {
            if (ModelState.IsValid)
            {
                await studentFeedbackService.SendFeedbackForm(form);
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }

        [Authorize(Roles = "Admin, Edu")]
        [HttpGet]
        public IActionResult GetAllStudentFeedbacks()
        {
            if (User.IsInRole("Edu")) 
            {
                var eduFeedbacks = studentFeedbackService.GetAllEduFeedbacks();
                return View(eduFeedbacks);
            }

            var feedbacks = studentFeedbackService.GetAllFeedBacks();
            return View(feedbacks);
        }
    }
}

StudentsRegistration/StudentsRegistration/Controllers/StudentsRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Common.Enums.SortEnums;
using Common.Models.StudentsPanelModels;
using Domain.Entities;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace StudentsRegistrationPanel.Controllers
{
    public class StudentsRegisterController : Controller
    {
        private readonly IStudentInfoService studentInfoService;
        private readonly IValidateService validateService;
        private AppDbContext context;

        public StudentsRegisterController(IStudentInfoService studentInfoService, AppDbContext context, IValidateService validateService)
        {
            this.studentInfoService = studentInfoService;
            this.context = context;
            this.validateService = validateService;
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public async Task<IActionResult> RegisterStudent()
        {
            if (await studentInfoService.IsStudentInfoExist())
            {
                return View("AlreadyExist");
            }

            AddViewBags();
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> RegisterStudent(StudentRegistrationModel model)
        {
            ValidateModel(model);

            if (ModelState.IsValid)
            {
                await studentInfoService.RegisterStudent(model);
                return RedirectToAction("Index", "Home");
            }

            AddViewBags();
            return View(model);
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Edit()
        {
            AddViewBags();

            var studentInfo = studentInfoService.GetStudentInfo();
            if (studentInfo == null)
            {
                return View("NotFound");
            }

            return View(studentInfo);
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> Edit(StudentRegistrationModel model)
        {
            ValidateModel(model);

            if (ModelState.IsValid)
            {
                await studentInfoService.UpdateStudentInfo(model);

                return RedirectToAction("Index", "Home");
            }
            AddViewBags();
            return View(model);
        }

        [Authorize(Roles = "Admin, Edu")]
        [HttpGet]
        public IActionResult GetAllStudentInfos(StudentsFilterModel filter, StudentInfoSortState sortOrder = StudentInfoSortState.FirstNameAsc)
        {
            var filterModel = new StudentsFilteredModel();
            var infos = studentInfoService.GetAllStudentInfo().Where(x=>!string.IsNullOrEmpty(x.FirstName));

            if (User.IsInRole("Edu"))
            {
                var currentInfo = studentInfoService.GetInfo();
                infos = infos.Where(x => x.UniversityName.Equals(currentInfo.UniversityName) && !string.IsNullOrEmpty(x.FirstName));
            }
            
            ViewData["FirstNameSort"] = sortOrder == StudentInfoSortState.FirstNameAsc ? StudentInfoSortState.FirstNameDesc : StudentInfoSortState.FirstNameAsc;
            ViewData["LastNameSort"] = sortOrder == StudentInfoSortState.LastNameAsc ? StudentInfoSortState.LastNameDesc : StudentInfoSortState.LastNameAsc;
            ViewData["MiddleNameSort"] = sortOrder == StudentInfoSortState.MiddleNameAsc ? StudentInfoSortState.MiddleNameDesc : StudentInfoSortState.MiddleNameAsc;
            ViewData["DateBornSort"] = sortOrder == StudentInfoSortState.DateBornAsc ? StudentInfoSortState.DateBornDesc : StudentInfoSortState.DateBornAsc;
            ViewData["CountryNameSort"] = sortOrder == StudentInfoSortState.CountryNameAsc ? StudentInfoSortState.CountryNameDesc : StudentInfoSortState.CountryNameAsc;
            ViewData["UniversityNameSort"] = sortOrder == StudentInfoSortState.UniversityNameAsc ? StudentInfoSortState.UniversityNameDesc : StudentInfoSortState.UniversityNameAsc;
            ViewData["YearOfEduStartSort"] = sortOrder == StudentInfoSortState.YearOfEduStartAsc ? StudentInfoSortState.YearOfEduStartDesc : StudentInfoSortState.YearOfEduStartAsc;
            ViewData["PhoneNumberSort"] = sortOrder == StudentInfoSortState.PhoneNumberAsc ? StudentInfoSortState.PhoneNumberDesc : StudentInfoSortState.PhoneNumberAsc;
            ViewData["EmailSort"] = sortOrder == StudentInfoSortState.EmailAsc ? StudentInfoSortState.EmailDesc : StudentInfoSortState.EmailAsc;

            infos = filterModel.FilterData(infos, filter);
            var sortedInfos = studentInfoService.SortData(infos, sortOrder);
            AddViewBags();

            return View(sortedInfos.AsEnumerable());
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditStudentInfo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AddViewBags();
            ViewBag.StudentInfoId = (int)id;
            var studentInfo = studentInfoService.GetStudentInfoById((int)id);
            return View("EditStudent", studentInfo);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> EditStudentInfo(StudentRegistrationModel model)
        {
            ValidateModel(model);

            if (ModelState.IsValid)
            {
                await studentInfoService.UpdateStudentInfo(model, model.Id);
                return RedirectToAction(nameof(GetAllStudentInfos));
            }

            AddViewBags();
            ViewBag.StudentInfoId = model.Id;
            return View("EditStudent", model);
        }

        private void ValidateModel(StudentRegistrationModel model)
        {
            if (string.IsNullOrEmpty(model.PhoneNumber) || !validateService.ValidatePhone(model.PhoneNumber))
            {
                ModelState.AddModelError("PhoneNumber", "Неверный формат номера");
            }
            if (string.IsNullOrEmpty(model.ParentsContantNumber) || !validateService.ValidatePhone(model.ParentsContantNumber))
            {
                ModelState.AddModelError("ParentsContantNumber", "Неверный формат номера");
            }
        }

        private void AddViewBags()
        {
            ViewBag.EducationProgramms = new SelectList(context.EducationProgramms, "Id", "Name");
            ViewBag.EducationTypes = new SelectList(context.EducationTypes, "Id", "Name");
            ViewBag.StudentStatuses = new SelectList(context.StudentStatuses, "Id", "Name");
        }
    }
}

StudentsRegistration/StudentsRegistration/Views/Shared/AlreadyExist.cshtml
@{
    ViewData["Title"] = "AlreadyExist";
}

<h1>Ваша анкета уже заполнена, вы можете отредактировать ее в профиле</h1>

StudentsRegistration/StudentsRegistration/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
}

<h1>Ваша анкета не найдена, возможно вы ее не заполняли</h1>

StudentsRegistration/StudentsRegistration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Регистрация студентов</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #e4e4e2;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Регистрация студента</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentsRegister" asp-action="RegisterStudent">Заполнить форму</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("Edu"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentsRegister" asp-action="GetAllStudentInfos">Список студентов</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="StudentFeedback" asp-action="GetAllStudentFeedbacks">Список заявок</a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: #e4e4e2;" class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Регистрация студентов - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>