StudentsRegistration/StudentsRegistration/Controllers/StudentInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Common.Models.StudentsPanelModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace StudentsRegistrationPanel.Controllers
{
    public class StudentInfoController : Controller
    {
        private readonly IStudentInfoService studentInfoService;

        public StudentInfoController(IStudentInfoService studentInfoService)
        {
            this.studentInfoService = studentInfoService;
        }

        [Authorize(Roles = "Admin, Edu")]
        [HttpPost]
        public string GetStudentsReportExcel()
        {
            if (User.IsInRole("Edu")) 
            {
                var studentsInfoEdu = studentInfoService.GetAllStudentInfo();
                var currentInfo = studentInfoService.GetInfo();
                studentsInfoEdu = studentsInfoEdu.Where(x => x.UniversityName.Equals(currentInfo.UniversityName) && !string.IsNullOrEmpty(x.FirstName));

                var resultEdu = studentInfoService.ExportStudentInfoExcel(studentsInfoEdu, Guid.NewGuid().ToString());
                return resultEdu;
            }
            var studentsInfo = studentInfoService.GetAllStudentInfo().Where(x => !string.IsNullOrEmpty(x.FirstName));

            var result = studentInfoService.ExportStudentInfoExcel(studentsInfo, Guid.NewGuid().ToString());
            return result;
        }
    }
}

StudentsRegistration/StudentsRegistration/Controllers/StudentsRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Services.Interfaces;
using Common.Enums.SortEnums;
using Common.Models.StudentsPanelModels;
using Domain.Entities;
using Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace StudentsRegistrationPanel.Controllers
{
    public class StudentsRegisterController : Controller
    {
        private readonly IStudentInfoService studentInfoService;
        private readonly IValidateService validateService;
        private AppDbContext context;

        public StudentsRegisterController(IStudentInfoService studentInfoService, AppDbContext context, IValidateService validateService)
        {
            this.studentInfoService = studentInfoService;
            this.context = context;
            this.validateService = validateService;
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public async Task<IActionResult> RegisterStudent()
        {
            if (await studentInfoService.IsStudentInfoExist())
            {
                return View("AlreadyExist");
            }

            AddViewBags();
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> RegisterStudent(StudentRegistrationModel model)
        {
            ValidateModel(model);

            if (ModelState.IsValid)
            {
                await studentInfoService.RegisterStudent(model);
                return RedirectToAction("Index", "Home");
            }

            AddViewBags();
            return View(model);
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Edit()
        {
            AddViewBags();

            var studentInfo = studentInfoService.GetStudentInfo();
            if (studentInfo == null)
            {
                return View("NotFound");
            }

            return View(studentInfo);
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> Edit(StudentRegistrationModel model)
        {
            ValidateModel(model);

            if (ModelState.IsValid)
            {
                await studentInfoService.UpdateStudentInfo(model);

                return RedirectToAction("Index", "Home");
            }
            AddViewBags();
            return View(model);
        }

        [Authorize(Roles = "Admin, Edu")]
        [HttpGet]
        public IActionResult GetAllStudentInfos(StudentsFilterModel filter, StudentInfoSortState sortOrder = StudentInfoSortState.FirstNameAsc)
        {
            var filterModel = new StudentsFilteredModel();
            var infos = studentInfoService.GetAllStudentInfo().Where(x=>!string.IsNullOrEmpty(x.FirstName));

            if (User.IsInRole("Edu"))
            {
                var currentInfo = studentInfoService.GetInfo();
                infos = infos.Where(x => x.UniversityName.Equals(currentInfo.UniversityName) && !string.IsNullOrEmpty(x.FirstName));
            }
            
            ViewData["FirstNameSort"] = sortOrder == StudentInfoSortState.FirstNameAsc ? StudentInfoSortState.FirstNameDesc : StudentInfoSortState.FirstNameAsc;
            ViewData["LastNameSort"] = sortOrder == StudentInfoSortState.LastNameAsc ? StudentInfoSortState.LastNameDesc : StudentInfoSortState.LastNameAsc;
            ViewData["MiddleNameSort"] = sortOrder == StudentInfoSortState.MiddleNameAsc ? StudentInfoSortState.MiddleNameDesc : StudentInfoSortState.MiddleNameAsc;
            ViewData["DateBornSort"] = sortOrder == StudentInfoSortState.DateBornAsc ? StudentInfoSortState.DateBornDesc : StudentInfoSortState.DateBornAsc;
            ViewData["CountryNameSort"] = sortOrder == StudentInfoSortState.CountryNameAsc ? StudentInfoSortState.CountryNameDesc : StudentInfoSortState.CountryNameAsc;
            ViewData["UniversityNameSort"] = sortOrder == StudentInfoSortState.UniversityNameAsc ? StudentInfoSortState.UniversityNameDesc : StudentInfoSortState.UniversityNameAsc;
            ViewData["YearOfEduStartSort"] = sortOrder == StudentInfoSortState.YearOfEduStartAsc ? StudentInfoSortState.YearOfEduStartDesc : StudentInfoSortState.YearOfEduStartAsc;
            ViewData["PhoneNumberSort"] = sortOrder == StudentInfoSortState.PhoneNumberAsc ? StudentInfoSortState.PhoneNumberDesc : StudentInfoSortState.PhoneNumberAsc;
            ViewData["EmailSort"] = sortOrder == StudentInfoSortState.EmailAsc ? StudentInfoSortState.EmailDesc : StudentInfoSortState.EmailAsc;

            infos = filterModel.FilterData(infos, filter);
            var sortedInfos = studentInfoService.SortData(infos, sortOrder);
            AddViewBags();

            return View(sortedInfos.AsEnumerable());
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditStudentInfo(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AddViewBags();
            ViewBag.StudentInfoId = (int)id;
            var studentInfo = studentInfoService.GetStudentInfoById((int)id);
            return View("EditStudent", studentInfo);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> EditStudentInfo(StudentRegistrationModel model)
        {
            ValidateModel(model);

            if (ModelState.IsValid)
            {
                await studentInfoService.UpdateStudentInfo(model, model.Id);
                return RedirectToAction(nameof(GetAllStudentInfos));
            }

            AddViewBags();
            ViewBag.StudentInfoId = model.Id;
            return View("EditStudent", model);
        }

        private void ValidateModel(StudentRegistrationModel model)
        {
            if (string.IsNullOrEmpty(model.PhoneNumber) || !validateService.ValidatePhone(model.PhoneNumber))
            {
                ModelState.AddModelError("PhoneNumber", "Неверный формат номера");
            }
            if (string.IsNullOrEmpty(model.ParentsContantNumber) || !validateService.ValidatePhone(model.ParentsContantNumber))
            {
                ModelState.AddModelError("ParentsContantNumber", "Неверный формат номера");
            }
        }

        private void AddViewBags()
        {
            ViewBag.EducationProgramms = new SelectList(context.EducationProgramms, "Id", "Name");
            ViewBag.EducationTypes = new SelectList(context.EducationTypes, "Id", "Name");
            ViewBag.StudentStatuses = new SelectList(context.StudentStatuses, "Id", "Name");
        }
    }
}

StudentsRegistration/StudentsRegistration/Views/StudentsRegister/Edit.cshtml
@model Common.Models.StudentsPanelModels.StudentRegistrationModel
@{
    ViewData["Title"] = "Edit";
    var educationProgramms = (IEnumerable<SelectListItem>)ViewBag.EducationProgramms;
    var educationTypes = (IEnumerable<SelectListItem>)ViewBag.EducationTypes;
    var studentStatuses = (IEnumerable<SelectListItem>)ViewBag.StudentStatuses;
}

<h1>Информация о студенте</h1>

<form asp-action="Edit" method="post" style="color:aliceblue">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="FirstName">Имя</label>
            <input asp-for="FirstName" type="text" class="form-control">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="LastName">Фамилия</label>
            <input asp-for="LastName" type="text" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="MiddleName">Отчество</label>
            <input asp-for="MiddleName" type="text" class="form-control">
            <span asp-validation-for="MiddleName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="DateBorn">Дата рождения</label>
            <input asp-for="DateBorn" type="date" class="form-control">
            <span asp-validation-for="DateBorn" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" type="email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
            <label asp-for="PhoneNumber">Контактные данные</label>
            <input asp-for="PhoneNumber" pattern="[0-9]*" type="number" class="form-control" placeholder="996">
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>
    <h4>Информация об учебном заведении</h4>
    <div class="form-group">
        <label asp-for="UniversityName">Название учебного заведения</label>
        <input asp-for="UniversityName" type="text" class="form-control" placeholder="Кыргызский национальный университет">
        <span asp-validation-for="UniversityName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Speciality">Специальность</label>
        <input asp-for="Speciality" type="text" class="form-control" placeholder="Юриспруденция">
        <span asp-validation-for="Speciality" class="text-danger"></span>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="CountryName">Страна обучения</label>
            <input asp-for="CountryName" type="text" class="form-control">
            <span asp-validation-for="CountryName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="YearOfEducationStart">Год поступления</label>
            <input asp-for="YearOfEducationStart" type="date" class="form-control">
            <span asp-validation-for="YearOfEducationStart" class="text-danger"></span>
            <label asp-for="EducationProgrammId">Программа образования</label>
            <select asp-for="EducationProgrammId" class="form-control" asp-items=@educationProgramms>
                <option selected>Выберите...</option>
            </select>
            <span asp-validation-for="EducationProgrammId" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="EducationTypeId">Форма обучения</label>
            <select asp-for="EducationTypeId" class="form-control" asp-items=@educationTypes>
                <option selected>Выберите...</option>
            </select>
            <span asp-validation-for="EducationTypeId" class="text-danger"></span>
            <label asp-for="StatusId">Статус</label>
            <select asp-for="StatusId" class="form-control" asp-items=@studentStatuses>
                <option selected>Выберите...</option>
            </select>
            <span asp-validation-for="StatusId" class="text-danger"></span>
        </div>
    </div>
    <h4>Контактные данные родителей или членов семьи</h4>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="ParentFirstName">Имя попечителя</label>
            <input asp-for="ParentFirstName" type="text" class="form-control">
            <span asp-validation-for="ParentFirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="ParentRelation">Степень родства</label>
            <input asp-for="ParentRelation" type="text" class="form-control">
            <span asp-validation-for="ParentRelation" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="ParentLastName">Фамилия попечителя</label>
            <input asp-for="ParentLastName" type="text" class="form-control">
            <span asp-validation-for="ParentLastName" class="text-danger"></span>
            <label asp-for="ParentMiddleName">Отчество попечителя</label>
            <input asp-for="ParentMiddleName" type="text" class="form-control">
            <span asp-validation-for="ParentMiddleName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="ParentsContantNumber">Контактные данные</label>
            <input asp-for="ParentsContantNumber" pattern="[0-9]*" type="number" class="form-control" placeholder="996">
            <span asp-validation-for="ParentsContantNumber" class="text-danger"></span>
            <label asp-for="ParentsEmail">Email</label>
            <input asp-for="ParentsEmail" type="email" class="form-control">
            <span asp-validation-for="ParentsEmail" class="text-danger"></span>
        </div>
    </div>
    <h4>Предыдущее образование</h4>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="LastEducationSchoolName">Школа</label>
            <input asp-for="LastEducationSchoolName" type="text" class="form-control">
            <span asp-validation-for="LastEducationSchoolName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="LastEducationUniversityName">ВУЗ</label>
            <input asp-for="LastEducationUniversityName" type="text" class="form-control">
            <span asp-validation-for="LastEducationUniversityName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input asp-for="IsAcceptDataSharing" class="form-check-input" type="checkbox">
            <label asp-for="IsAcceptDataSharing" class="form-check-label">
                Я согласен на обработку моих данных
            </label>
        </div>
    </div>
    <button style="margin-bottom:90px;" type="submit" class="btn btn-primary">Сохранить</button>
</form>

StudentsRegistration/StudentsRegistration/Views/StudentsRegister/EditStudent.cshtml
@model Common.Models.StudentsPanelModels.StudentRegistrationModel
@{
    ViewData["Title"] = "Edit";
    var educationProgramms = (IEnumerable<SelectListItem>)ViewBag.EducationProgramms;
    var educationTypes = (IEnumerable<SelectListItem>)ViewBag.EducationTypes;
    var studentStatuses = (IEnumerable<SelectListItem>)ViewBag.StudentStatuses;
    var studentInfoId = (int)ViewBag.StudentInfoId;
}

<h1>Информация о студенте</h1>

<form asp-action="EditStudentInfo" method="post" style="color:aliceblue">
    <input asp-for="Id" value="@studentInfoId" hidden/>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="FirstName">Имя</label>
            <input asp-for="FirstName" type="text" class="form-control">
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="LastName">Фамилия</label>
            <input asp-for="LastName" type="text" class="form-control">
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="MiddleName">Отчество</label>
            <input asp-for="MiddleName" type="text" class="form-control">
            <span asp-validation-for="MiddleName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="DateBorn">Дата рождения</label>
            <input asp-for="DateBorn" type="date" class="form-control">
            <span asp-validation-for="DateBorn" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Email">Email</label>
            <input asp-for="Email" type="email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
            <label asp-for="PhoneNumber">Контактные данные</label>
            <input asp-for="PhoneNumber" pattern="[0-9]*" type="number" class="form-control" placeholder="996">
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>
    <h4>Информация об учебном заведении</h4>
    <div class="form-group">
        <label asp-for="UniversityName">Название учебного заведения</label>
        <input asp-for="UniversityName" type="text" class="form-control" placeholder="Кыргызский национальный университет">
        <span asp-validation-for="UniversityName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Speciality">Специальность</label>
        <input asp-for="Speciality" type="text" class="form-control" placeholder="Юриспруденция">
        <span asp-validation-for="Speciality" class="text-danger"></span>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="CountryName">Страна обучения</label>
            <input asp-for="CountryName" type="text" class="form-control">
            <span asp-validation-for="CountryName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="YearOfEducationStart">Год поступления</label>
            <input asp-for="YearOfEducationStart" type="date" class="form-control">
            <span asp-validation-for="YearOfEducationStart" class="text-danger"></span>
            <label asp-for="EducationProgrammId">Программа образования</label>
            <select asp-for="EducationProgrammId" class="form-control" asp-items=@educationProgramms>
                <option selected>Выберите...</option>
            </select>
            <span asp-validation-for="EducationProgrammId" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="EducationTypeId">Форма обучения</label>
            <select asp-for="EducationTypeId" class="form-control" asp-items=@educationTypes>
                <option selected>Выберите...</option>
            </select>
            <span asp-validation-for="EducationTypeId" class="text-danger"></span>
            <label asp-for="StatusId">Статус</label>
            <select asp-for="StatusId" class="form-control" asp-items=@studentStatuses>
                <option selected>Выберите...</option>
            </select>
            <span asp-validation-for="StatusId" class="text-danger"></span>
        </div>
    </div>
    <h4>Контактные данные родителей или членов семьи</h4>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="ParentFirstName">Имя попечителя</label>
            <input asp-for="ParentFirstName" type="text" class="form-control">
            <span asp-validation-for="ParentFirstName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="ParentRelation">Степень родства</label>
            <input asp-for="ParentRelation" type="text" class="form-control">
            <span asp-validation-for="ParentRelation" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="ParentLastName">Фамилия попечителя</label>
            <input asp-for="ParentLastName" type="text" class="form-control">
            <span asp-validation-for="ParentLastName" class="text-danger"></span>
            <label asp-for="ParentMiddleName">Отчество попечителя</label>
            <input asp-for="ParentMiddleName" type="text" class="form-control">
            <span asp-validation-for="ParentMiddleName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-2">
            <label asp-for="ParentsContantNumber">Контактные данные</label>
            <input asp-for="ParentsContantNumber" pattern="[0-9]*" type="number" class="form-control" placeholder="996">
            <span asp-validation-for="ParentsContantNumber" class="text-danger"></span>
            <label asp-for="ParentsEmail">Email</label>
            <input asp-for="ParentsEmail" type="email" class="form-control">
            <span asp-validation-for="ParentsEmail" class="text-danger"></span>
        </div>
    </div>
    <h4>Предыдущее образование</h4>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="LastEducationSchoolName">Школа</label>
            <input asp-for="LastEducationSchoolName" type="text" class="form-control">
            <span asp-validation-for="LastEducationSchoolName" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="LastEducationUniversityName">ВУЗ</label>
            <input asp-for="LastEducationUniversityName" type="text" class="form-control">
            <span asp-validation-for="LastEducationUniversityName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input asp-for="IsAcceptDataSharing" class="form-check-input" type="checkbox">
            <label asp-for="IsAcceptDataSharing" class="form-check-label">
                Я согласен на обработку моих данных
            </label>
        </div>
    </div>
    <button style="margin-bottom:90px;" type="submit" class="btn btn-primary">Сохранить</button>
</form>

StudentsRegistration/StudentsRegistration/Views/StudentsRegister/GetAllStudentInfos.cshtml
@model IEnumerable<Domain.Entities.StudentsInfo>
@{
    ViewData["Title"] = "GetAllStudentInfos";
    var educationProgramms = (IEnumerable<SelectListItem>)ViewBag.EducationProgramms;
    var educationTypes = (IEnumerable<SelectListItem>)ViewBag.EducationTypes;
    var studentStatuses = (IEnumerable<SelectListItem>)ViewBag.StudentStatuses;
}

<button data-toggle="modal" data-target="#filtermodal" type="button" style="margin-bottom: 20px;" class="btn btn-outline-info">Фильтр</button>

<table class="table" style="font-size: 10px; color:aliceblue;">
    <thead>
    <tr>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.FirstNameSort">
                Имя
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.LastNameSort">
                Фамилия
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.MiddleNameSort">
                Отчество
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.DateBornSort">
                Дата рождения
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.CountryNameSort">
                Страна обучения
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.UniversityNameSort">
                Название учебного заведения
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.YearOfEduStartSort">
                Год поступления
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.PhoneNumberSort">
                Контактный номер
            </a>
        </th>
        <th>
            <a asp-action="GetAllStudentInfos" asp-route-sortOrder="@ViewBag.EmailSort">
                Почта
            </a>
        </th>
        <th>
            Специальность
        </th>
        <th>
            Программа обучения
        </th>
        <th>
            Тип обучения
        </th>
        <th>
            Статус обучения
        </th>
        <th>
            Согласен на обработку данных
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MiddleName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateBorn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CountryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UniversityName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearOfEducationStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Speciality)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EducationProgramm.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EducationType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentStatus.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsAcceptDataSharing)
                </td>
                <td>
                    <a asp-action="EditStudentInfo" asp-route-id="@item.Id">Подробней</a> 
                </td>
            </tr>
        }
    }
    </tbody>
</table>

<button id="exportExcel" asp-controller="StudentInfo" asp-action="GetStudentsReportExcel" style="margin-top: 10px; margin-bottom:90px;" class="btn btn-outline-info">Экспорт данных в Excel</button>

<div class="modal fade" id="filtermodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form style="color:black">
            <div class="modal-content">
                <div class="modal-header">
                    <label style="color:black;">Фильтр</label>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="firstNameFilter">Имя</label>
                        <input name="FirstName" type="text" class="form-control" id="firstNameFilter" placeholder="Василий">
                        <label for="lastNameFilter">Фамилия</label>
                        <input name="LastName" type="text" class="form-control" id="lastNameFilter" placeholder="Аманов">
                        <label for="middleNameFilter">Отчество</label>
                        <input name="MiddleName" type="text" class="form-control" id="middleNameFilter" placeholder="Василий">
                        <label for="exampleFormControlInput1">Почта</label>
                        <input name="Email" type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
                    </div>
                        <div class="form-group">
                            <label for="educationTypeFilter">Тип обучения</label>
                            <select name="EducationTypeId" class="form-control" id="educationTypeFilter" asp-items=@educationTypes>
                                <option selected>Выберите...</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="educationProgrammFilter">Программа обучения</label>
                            <select name="EducationProgrammId" class="form-control" id="educationProgrammFilter" asp-items=@educationProgramms>
                                <option selected>Выберите...</option>
                            </select>
                        </div>
                         <div class="form-group">
                            <label for="studentStatusFilter">Статус</label>
                            <select name="StudentStatusId" class="form-control" id="studentStatusFilter" asp-items=@studentStatuses>
                                <option selected>Выберите...</option>
                            </select>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button id="send" type="submit" class="btn btn-primary">Отфильтровать</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).on("click", "#exportExcel", function () {
            $.ajax({
                type: "POST",
                url: '/StudentInfo/GetStudentsReportExcel/'
            }).done(function (data) {
                var url = data;
                var a = document.createElement('a');
                a.href = data;
                a.download = 'report.xlsx';
                a.click();
                window.URL.revokeObjectURL(url);
            }).fail(function () {
                alert("Ошибка при создании отчета")
            });
        });
    </script>
}